server.port=7777
spring.application.name=springprueba
config.usuario = gabog
config.codigo = 1234 
config.mensajes = Sos fero bobazooooooooooo 
config.valores = valor1, valor2, valor3, valor4
config.beta= beta
config.alpha= alpha
config.delta= delta
spring.datasource.url=jdbc:postgresql://localhost:5432/Nhasilvia
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

