server.port=7777
spring.application.name=springprueba
config.usuario = gabog
config.codigo = 1234 
config.mensajes = Sos fero bobazooooooooooo 
config.valores = valor1, valor2, valor3, valor4
config.beta= beta
config.alpha= alpha
config.delta= delta
